import React from 'react';
import { Box, Container, Typography } from '@mui/material';

const termsOfService = {
    lastUpdated: "March 2025",
    companyName: "Lambda Quantum Ltd",
    companyNumber: "16290769",
    registeredOffice: "71-75 Shelton Street, Covent Garden, London, United Kingdom, WC2H 9JQ",
    incorporationDate: "March 4, 2025",

    introduction: `Welcome to Lambda Quantum Ltd! These Terms of Service ("Terms") govern your use of our AI API integration services. By accessing or using Lambda Quantum's services, you agree to these Terms. If you do not agree, please do not use our services.`,

    servicesProvided: {
        section1: "1. Services Provided",
        description: `Lambda Quantum Ltd provides AI API aggregation and integration services that allow users to access multiple large language models through a single API.`,
        features: [
            "Pay-as-you-go Pricing: Users are charged based on API usage.",
            "Free Trial: New users receive a free usage quota.",
            "Commercial Use Allowed: Users may build and sell products based on Lambda Quantum’s API."
        ]
    },

    userObligations: {
        section2: "3. User Obligations & Restrictions",
        permittedUse: [
            "You may use Lambda Quantum’s API for lawful business and commercial purposes, including but not limited to:",
            "Application development",
            "AI-enhanced automation",
            "AI-driven analytics"
        ],
        prohibitedUse: [
            "You must not use Lambda Quantum’s API for any unlawful, fraudulent, or misleading activity.",
            "Generating, distributing, or assisting in the creation of sensitive, harmful, illegal, violent, or unethical content.",
            "Disrupting or interfering with the operation of Lambda Quantum’s infrastructure.",
            "Reverse engineering, modifying, or attempting to hack the API.",
            "Using the API for activities restricted by international sanctions or trade laws."
        ]
    },

    dataStorage: {
        section3: "4. Data Storage & User Content",
        description: `API responses may be stored: Users may store and retain responses from Lambda Quantum’s API for their own applications. You are solely responsible for how you use, modify, and distribute stored responses.`
    },

    pricing: {
        section4: "5. Pricing, Billing & Refunds",
        payAsYouGo: `Lambda Quantum charges users based on API usage. Fees are subject to change, and any modifications will be communicated in advance.`,
        freeTrial: `New users receive a free usage quota. Once exceeded, further API usage will be billed accordingly.`,
        refunds: `Unused API credits are refundable upon request. Refunds are not provided for used API credits.`
    },

    serviceAvailability: {
        section5: "6. Service Availability & Liability",
        noGuarantees: `Lambda Quantum does not guarantee that the API responses are accurate, error-free, or suitable for any specific purpose.`,
        limitationOfLiability: `Lambda Quantum Ltd shall not be held liable for any errors, inaccuracies, or unintended outputs generated by the API.`
    },

    termination: {
        section6: "7. Termination of Service",
        description: `Lambda Quantum reserves the right to terminate or restrict API access if a user violates any section of these Terms.`
    },

    geographicRestrictions: {
        section7: "8. Geographic Restrictions",
        description: `Lambda Quantum’s services are not available to users from the following countries: United Kingdom, Mainland China.`
    },

    intellectualProperty: {
        section8: "9. Intellectual Property Rights",
        description: `All intellectual property rights, trademarks, and proprietary technology related to Lambda Quantum’s API remain the exclusive property of Lambda Quantum Ltd.`
    },

    changesToTerms: {
        section9: "10. Changes to These Terms",
        description: `Lambda Quantum may update these Terms periodically. If changes are made, they will be communicated via website updates at https://www.lq-ltd.com.`
    },

    governingLaw: {
        section10: "11. Governing Law & Jurisdiction",
        description: `These Terms are governed by the laws of Hong Kong. Any disputes arising from these Terms shall be resolved in Hong Kong courts.`
    },

    contactInformation: {
        section11: "12. Contact Information",
        email: "📩 Email: support@lq-ltd.com",
        website: "🌐 Website: https://www.lq-ltd.com",
        copyright: "© 2025 Lambda Quantum Ltd. All rights reserved."
    }
};

const TermsOfService = () => {
  return (
    <Container maxWidth="md">
      <Box sx={{ padding: 4, backgroundColor: '#fff', borderRadius: 2, boxShadow: 1, my: 4 }}>
        <Typography variant="h4" gutterBottom sx={{ mb: 4 }}>
          Terms of Service
        </Typography>
        
        <Typography variant="subtitle2" color="text.secondary" paragraph>
          Last Updated: {termsOfService.lastUpdated}
        </Typography>

        <Typography variant="body1" paragraph sx={{ whiteSpace: 'pre-line' }}>
          {termsOfService.introduction}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.servicesProvided.section1}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.servicesProvided.description}
        </Typography>
        {termsOfService.servicesProvided.features.map((feature, index) => (
          <Typography key={index} variant="body1" paragraph>
            • {feature}
          </Typography>
        ))}

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.userObligations.section2}
        </Typography>
        <Typography variant="h6" sx={{ mt: 3, mb: 1 }}>
          Permitted Use
        </Typography>
        {termsOfService.userObligations.permittedUse.map((use, index) => (
          <Typography key={index} variant="body1" paragraph>
            • {use}
          </Typography>
        ))}
        <Typography variant="h6" sx={{ mt: 3, mb: 1 }}>
          Prohibited Use
        </Typography>
        {termsOfService.userObligations.prohibitedUse.map((use, index) => (
          <Typography key={index} variant="body1" paragraph>
            • {use}
          </Typography>
        ))}

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.dataStorage.section3}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.dataStorage.description}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.pricing.section4}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.pricing.payAsYouGo}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.pricing.freeTrial}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.pricing.refunds}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.serviceAvailability.section5}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.serviceAvailability.noGuarantees}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.serviceAvailability.limitationOfLiability}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.termination.section6}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.termination.description}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.geographicRestrictions.section7}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.geographicRestrictions.description}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.intellectualProperty.section8}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.intellectualProperty.description}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.changesToTerms.section9}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.changesToTerms.description}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.governingLaw.section10}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.governingLaw.description}
        </Typography>

        <Typography variant="h5" sx={{ mt: 4, mb: 2 }}>
          {termsOfService.contactInformation.section11}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.contactInformation.email}
        </Typography>
        <Typography variant="body1" paragraph>
          {termsOfService.contactInformation.website}
        </Typography>
        <Typography variant="body2" sx={{ mt: 4, textAlign: 'center' }}>
          {termsOfService.contactInformation.copyright}
        </Typography>
      </Box>
    </Container>
  );
};

export default TermsOfService;